version: '3.8'

networks:
  dmznet:
    driver: bridge

services:
  intake-web:
    build:
      context: ./chmr-intake-web
    env_file:
      - .env
    environment:
      DAL_HOST: http://chmr-dmz-dal:5000
    ports:
      - "${PORT_INTAKE}:3000" # Expose intake-web to the host
    networks:
      - dmznet

  maint:
    build:
      context: ./chmr-dmz-maint
    env_file:
      - .env
    environment:
      DAL_HOST: http://chmr-dmz-dal:5000
    ports:
      - "${PORT_MAINT}:3000" # Expose maint to the host
    networks:
      - dmznet

  chmr-dmz-redis:
    image: redis:7
    networks:
      - dmznet

  chmr-dmz-dal:
    build:
      context: ./chmr-dmz-dal
    env_file:
      - .env
    environment:
      REDIS_HOST: redis://chmr-dmz-redis:6379
    networks:
      - dmznet