networks:
  dmznet:
    driver: bridge
  dmpnet:
    driver: bridge

services:
  chmr-dmz-dal:
    build:
      context: ./chmr-dmz-dal
    env_file:
      - .env
    environment:
      REDIS_HOST: redis://chmr-dmz-redis:6379
    networks:
      - dmznet
    depends_on:
      - chmr-dmz-redis # Ensure Redis starts before DAL
    volumes:
      - filedata:/usr/server/app/files

  intake-web:
    build:
      context: ./chmr-intake-web
    env_file:
      - .env
    environment:
      REACT_APP_DAL_HOST: http://chmr-dmz-dal:5000 # DAL is accessible via dmznet
    ports:
      - "${PORT_INTAKE}:80" # Expose container's port to the host
    networks:
      - dmznet
    depends_on:
      - chmr-dmz-dal # Ensure DAL starts before intake-web

  maint:
    build:
      context: ./chmr-dmz-maint
    env_file:
      - .env
    environment:
      REACT_APP_DAL_HOST: http://chmr-dmz-dal:5000 # DAL is accessible via dmznet
    ports:
      - "${PORT_MAINT}:80" # Expose maint to the host
    networks:
      - dmznet
    depends_on:
      - chmr-dmz-dal # Ensure DAL starts before maint

  chmr-dmz-redis:
    image: redis:7
    networks:
      - dmznet
  
  chmr-dmp-postgres:
    build:
      context: ./chmr-dmp-postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dmpnet

volumes:
  filedata:
  postgres-data:
