networks:
  chmrdmznet:
    driver: bridge
  chmrdmpnet:
    driver: bridge

services:
  # A Node.js/Express service for handling API requests and interacting with the database.
  chmr-dmz-dal:
    build:
      context: ./chmr-dmz-dal
    env_file:
      - .env
    environment:
      REDIS_HOST: redis://chmr-dmz-redis:6379
    networks:
      - chmrdmznet
    depends_on:
      - chmr-dmz-redis # Ensure Redis starts before DAL
    volumes:
      - filedata:/usr/server/app/files

  # Web page to report civilian harm
  intake-web:
    build:
      context: ./chmr-intake-web
    env_file:
      - .env
    environment:
      REACT_APP_DAL_HOST: http://chmr-dmz-dal:5000 # DAL is accessible via dmznet
    ports:
      - "${PORT_INTAKE}:80" # Expose container's port to the host
    networks:
      - chmrdmznet
    depends_on:
      - chmr-dmz-dal # Ensure DAL starts before intake-web

  # A React-based application for managing reports.
  maint:
    build:
      context: ./chmr-dmz-maint
    env_file:
      - .env
    environment:
      REACT_APP_DAL_HOST: http://chmr-dmz-dal:5000 # DAL is accessible via dmznet
    ports:
      - "${PORT_DMZ_MAINT}:80" # Expose maint to the host
    networks:
      - chmrdmznet
    depends_on:
      - chmr-dmz-dal # Ensure DAL starts before maint

  # A redis container used for caching and session management.
  chmr-dmz-redis:
    image: redis:7
    networks:
      - chmrdmznet
  
  # A container to start the postgres database.
  chmr-dmp-postgres:
    build:
      context: ./chmr-dmp-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - chmrdmpnet

  # A Node.js/Express service for handling API requests and interacting with the database.
  chmr-dmp-dal:
    build:
      context: ./chmr-dmp-dal
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres://chmr-dmp-postgres:5342
    networks:
      - chmrdmpnet
    depends_on:
      - chmr-dmp-postgres
    volumes:
      - filedata:/usr/server/app/files

volumes:
  filedata:
  postgres-data:
